version: "3.8"

services:
  frontend:
    build:
      context: ./public
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      - app_network
    restart: unless-stopped
    volumes:
      - ./public:/usr/src/app
      - /usr/src/app/node_modules # Prevent overwriting node_modules

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: api_container
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/mydb
    networks:
      - app_network
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:6.0
    container_name: mongo_container
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
